model_params:
  name: "MAF"
  type: "flow"
  params:
    features: 1024
    hidden_features: 1000
    context_features: 1
    num_layers: 10
    num_blocks_per_layer: 5

dataset:
  name: "flow"
  dataset_params:
    data_path_train_x: "logs/celeba/DFCVAE/version_1/latent_space/z_train.csv"
    data_path_train_y: "logs/celeba/DFCVAE/version_1/latent_space/y_train_gender.csv"
    data_path_valid_x: "logs/celeba/DFCVAE/version_1/latent_space/z_valid.csv"
    data_path_valid_y: "logs/celeba/DFCVAE/version_1/latent_space/y_valid_gender.csv"
    batch_size: 1024
    num_workers: 24

exp_params:
  patience: 25

trainer_params:
  gpus: '0'
  max_epochs: 1000

logging_params:
  save_dir: "logs/celeba/"
  name: "MAF"
  manual_seed: 1265
