model_params:
  name: "MAF"
  type: "flow"
  params:
    features: 2048
    hidden_features: 1000
    context_features: 40

dataset:
  name: "flow"
  dataset_params:
    data_path_train_x: "logs/celeba/MSP/msp_256/latent_space/z_train.csv"
    data_path_train_y: "logs/celeba/MSP/msp_256/latent_space/y_train.csv"
    data_path_valid_x: "logs/celeba/MSP/msp_256/latent_space/z_valid.csv"
    data_path_valid_y: "logs/celeba/MSP/msp_256/latent_space/y_valid.csv"
    batch_size: 1024
    num_workers: 24

exp_params:
  patience: 50

trainer_params:
  gpus: '0'
  max_epochs: 2000

logging_params:
  save_dir: "logs/celeba/"
  name: "MSP-MAF"
  manual_seed: 1265
