model_params:
  name: "MAF"
  type: "flow"
  params:
    features: 128
    hidden_features: 1024
    context_features: 55
    dropout_probability: 0.2
    batch_norm_within_layers: False
    batch_norm_between_layers: False

dataset:
  name: "flow"
  dataset_params:
    data_path_train_x: "logs/shapenet/PointFlow/all/latent_space/z_train_split.csv"
    data_path_train_y: "logs/shapenet/PointFlow/all/latent_space/y_train_ohe_split.csv"
    data_path_valid_x: "logs/shapenet/PointFlow/all/latent_space/z_valid_split.csv"
    data_path_valid_y: "logs/shapenet/PointFlow/all/latent_space/y_valid_ohe_split.csv"
    batch_size: 4096
    num_workers: 24

exp_params:
  patience: 50
  noise: 0.01

trainer_params:
  gpus: '0'
  max_epochs: 5000

logging_params:
  save_dir: "logs/shapenet/"
  name: "MAF"
  manual_seed: 1265
