model_params:
  name: "MAF"
  type: "flow"
  params:
    features: 40
    hidden_features: 100
    context_features: 10
    num_layers: 5
    batch_norm_within_layers: True
    batch_norm_between_layers: True

dataset:
  name: "flow"
  dataset_params:
    data_path_train_x: "logs/mnist/ConvAE/version_1/latent_space/z_train.csv"
    data_path_train_y: "logs/mnist/ConvAE/version_1/latent_space/y_train_ohe.csv"
    data_path_valid_x: "logs/mnist/ConvAE/version_1/latent_space/z_test.csv"
    data_path_valid_y: "logs/mnist/ConvAE/version_1/latent_space/y_test_ohe.csv"
    batch_size: 1024
    num_workers: 24

exp_params:
  patience: 50

trainer_params:
  gpus: 1
  max_epochs: 5000

logging_params:
  save_dir: "logs/mnist/"
  name: "MAF"
  manual_seed: 1265
