model_params:
  name: "ConvAE"
  type: "vae"
  params:
    latent_dim: 128

dataset:
  name: "mnist"
  dataset_params:
    data_dir: "data"
    batch_size: 1024
    num_workers: 24

exp_params:
  LR: 0.005
  M_N: 1

trainer_params:
  gpus: 1
  max_epochs: 5000

logging_params:
  save_dir: "logs/mnist"
  name: "ConvAE"
  manual_seed: 1265
