model_params:
  name: "ConvVAE"
  type: "vae"
  params:
    latent_dim: 128

dataset:
  name: "mnist"
  dataset_params:
    data_dir: "data"
    batch_size: 1024
    num_workers: 24

exp_params:
  LR: 0.005

trainer_params:
  gpus: '0'
  max_epochs: 5000

logging_params:
  save_dir: "logs/mnist"
  name: "ConvVAE"
  manual_seed: 1265
