model_params:
  name: 'DFCVAE'
  type: "vae"
  params:
    in_channels: 1
    latent_dim: 40

dataset:
  name: "mnist"
  dataset_params:
    data_dir: "data"
    batch_size: 1024
    num_workers: 24

exp_params:
  LR: 0.005
  M_N: 0.02

trainer_params:
  gpus: 1
  max_epochs: 100

logging_params:
  save_dir: "logs/mnist"
  name: "DFCVAE"
  manual_seed: 1265
