model_params:
  name: "MAF"
  params:
    features: 128
    hidden_features: 50
    context_features: 1
    num_layers: 10
    num_blocks_per_layer: 5

exp_params:
  data_path_train_x: "logs/DFCAE/version_0/latent_space/z_train.csv"
  data_path_train_y: "logs/DFCAE/version_0/latent_space/y_train_gender.csv"
  batch_size: 64

trainer_params:
  gpus: 1
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "MAF"
  manual_seed: 1265
