model_params:
  name: 'DFCVAE'
  type: "vae"
  params:
    in_channels: 3
    latent_dim: 128

dataset:
  name: "celeba"
  dataset_params:
    data_dir: "data"
    batch_size: 256
    num_workers: 24

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 100

logging_params:
  save_dir: "logs/celeba/"
  name: "DFCVAE"
  manual_seed: 1265
