model_params:
  name: "VAE"
  type: "vae"
  params:
    in_channels: 3
    latent_dim: 128

exp_params:
  dataset: celeba
  data_path: "data"
  batch_size: 256
  num_workers: 24
  patience: 25
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 100

logging_params:
  save_dir: "logs/celeba/"
  name: "VAE"
  manual_seed: 1265
