model_params:
  name: 'DFCVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: celeba
  data_path: "data"
  img_size: 64
  batch_size: 256 # Better to have a square number
  num_workers: 24
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  patience: 5

trainer_params:
  gpus: 1
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "DFCVAE"
  manual_seed: 1265
